# Generated by Django 5.1.15 on 2026-05-21 01:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("decks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("word", "Word"),
                            ("phrasal_verb", "Phrasal verb"),
                            ("idiom", "Idiom"),
                            ("collocation", "Collocation"),
                            ("expression", "Expression"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lemma", models.CharField(max_length=200)),
                ("source_language", models.CharField(max_length=8)),
                ("target_language", models.CharField(max_length=8)),
                ("data", models.JSONField(default=dict)),
                (
                    "source",
                    models.CharField(
                        choices=[("mcp", "MCP"), ("rest_api", "REST API"), ("manual", "Manual")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="decks.deck",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "type"], name="artifacts_a_user_id_c64738_idx"),
                    models.Index(fields=["user", "lemma"], name="artifacts_a_user_id_dfef71_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "deck", "type", "lemma"),
                        name="unique_artifact_per_user_deck_type_lemma",
                    )
                ],
            },
        ),
    ]
