# Generated by Django 5.1.15 on 2026-05-21 03:16

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artifacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("learning", "Learning"),
                            ("review", "Review"),
                            ("relearning", "Relearning"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("learned", "Learned"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("stability", models.FloatField(blank=True, null=True)),
                ("difficulty", models.FloatField(blank=True, null=True)),
                ("due_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reps", models.PositiveIntegerField(default=0)),
                ("lapses", models.PositiveIntegerField(default=0)),
                (
                    "artifact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_state",
                        to="artifacts.artifact",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "due_at"], name="reviews_rev_status_b97aa3_idx"),
                    models.Index(fields=["state", "due_at"], name="reviews_rev_state_f9f3de_idx"),
                ],
            },
        ),
    ]
