# Generated by Django 5.1.15 on 2026-05-21 03:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0001_initial"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reviewed_at", models.DateTimeField()),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Again"), (2, "Hard"), (3, "Good"), (4, "Easy")]
                    ),
                ),
                ("elapsed_days", models.FloatField()),
                ("scheduled_days", models.FloatField()),
                (
                    "state_before",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("learning", "Learning"),
                            ("review", "Review"),
                            ("relearning", "Relearning"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to="artifacts.artifact",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
                "indexes": [
                    models.Index(
                        fields=["artifact", "-reviewed_at"], name="reviews_rev_artifac_a6a0e2_idx"
                    )
                ],
            },
        ),
    ]
